import type { DeckEntry } from './types.ts';

export interface StarterDeck {
  /** Nome do deck como aparece no Arena. */
  name: string;
  /** Os cinco de uma cor vêm do tutorial; os dez de duas cores são trocados quando o Standard gira. */
  kind: 'mono' | 'dual';
  main: DeckEntry[];
}

/**
 * Os 15 decks iniciais que o MTG Arena dá a todo jogador, com 60 cartas cada e sem sideboard.
 *
 * Fonte: https://draftsim.com/mtg-arena-starter-decks/ (lido em 5 de outubro de 2026).
 * A Wizards publicou as listas dos dez decks de duas cores em novembro de 2024
 * (https://magic.wizards.com/en/news/mtg-arena/mtg-arena-announcements-november-18-2024),
 * mas eles foram revistos em 2025 e não achei uma lista oficial da versão atual; por isso a fonte
 * é de terceiros. O Arena troca esses decks de tempos em tempos: ao atualizar, confira todos.
 */
export const ARENA_STARTER_DECKS: readonly StarterDeck[] = [
  {
    name: 'Keep the Peace',
    kind: 'mono',
    main: [
      { name: 'Charmed Stray', quantity: 4 },
      { name: 'Fencing Ace', quantity: 2 },
      { name: 'Hallowed Priest', quantity: 4 },
      { name: 'Impassioned Orator', quantity: 3 },
      { name: 'Moorland Inquisitor', quantity: 2 },
      { name: 'Angel of Vitality', quantity: 2 },
      { name: 'Leonin Warleader', quantity: 2 },
      { name: 'Serra Angel', quantity: 1 },
      { name: 'Spiritual Guardian', quantity: 1 },
      { name: 'Angelic Guardian', quantity: 1 },
      { name: 'Inspiring Commander', quantity: 2 },
      { name: 'Goring Ceratops', quantity: 1 },
      { name: 'Tactical Advantage', quantity: 4 },
      { name: 'Confront the Assault', quantity: 1 },
      { name: 'Bond of Discipline', quantity: 1 },
      { name: 'Pacifism', quantity: 3 },
      { name: 'Angelic Reward', quantity: 1 },
      { name: 'Plains', quantity: 25 },
    ],
  },
  {
    name: 'Aerial Domination',
    kind: 'mono',
    main: [
      { name: 'Wall of Runes', quantity: 2 },
      { name: 'Sworn Guardian', quantity: 2 },
      { name: 'Waterkin Shaman', quantity: 3 },
      { name: 'Cloudkin Seer', quantity: 3 },
      { name: 'Warden of Evos Isle', quantity: 3 },
      { name: 'Octoprophet', quantity: 2 },
      { name: 'Soulblade Djinn', quantity: 2 },
      { name: 'Windstorm Drake', quantity: 2 },
      { name: 'Frilled Sea Serpent', quantity: 1 },
      { name: 'Riddlemaster Sphinx', quantity: 2 },
      { name: 'Windreader Sphinx', quantity: 1 },
      { name: 'Unsummon', quantity: 3 },
      { name: 'Glint', quantity: 2 },
      { name: 'Winged Words', quantity: 2 },
      { name: 'Sleep', quantity: 1 },
      { name: 'Overflowing Insight', quantity: 1 },
      { name: 'Waterknot', quantity: 3 },
      { name: 'Island', quantity: 25 },
    ],
  },
  {
    name: 'Cold-Blooded Killers',
    kind: 'mono',
    main: [
      { name: 'Sanitarium Skeleton', quantity: 2 },
      { name: 'Typhoid Rats', quantity: 2 },
      { name: 'Malakir Cullblade', quantity: 3 },
      { name: 'Vampire Opportunist', quantity: 2 },
      { name: 'Mardu Outrider', quantity: 2 },
      { name: 'Savage Gorger', quantity: 3 },
      { name: 'Skeleton Archer', quantity: 2 },
      { name: 'Sengir Vampire', quantity: 2 },
      { name: 'Soulhunter Rakshasa', quantity: 1 },
      { name: 'Nightmare', quantity: 1 },
      { name: 'Demon of Loathing', quantity: 2 },
      { name: 'Compound Fracture', quantity: 4 },
      { name: 'Cruel Cut', quantity: 1 },
      { name: 'Unlikely Aid', quantity: 3 },
      { name: 'Murder', quantity: 3 },
      { name: 'Bad Deal', quantity: 1 },
      { name: 'Eternal Thirst', quantity: 1 },
      { name: 'Swamp', quantity: 25 },
    ],
  },
  {
    name: 'Goblins Everywhere!',
    kind: 'mono',
    main: [
      { name: 'Tin Street Cadet', quantity: 3 },
      { name: 'Goblin Tunneler', quantity: 2 },
      { name: 'Nest Robber', quantity: 4 },
      { name: 'Molten Ravager', quantity: 2 },
      { name: 'Goblin Gang Leader', quantity: 2 },
      { name: 'Goblin Trashmaster', quantity: 1 },
      { name: 'Ogre Battledriver', quantity: 2 },
      { name: 'Immortal Phoenix', quantity: 1 },
      { name: 'Volcanic Dragon', quantity: 1 },
      { name: 'Siege Dragon', quantity: 2 },
      { name: 'Shock', quantity: 3 },
      { name: 'Storm Strike', quantity: 2 },
      { name: 'Burn Bright', quantity: 2 },
      { name: 'Inescapable Blaze', quantity: 2 },
      { name: 'Goblin Gathering', quantity: 4 },
      { name: 'Raid Bombardment', quantity: 2 },
      { name: 'Mountain', quantity: 25 },
    ],
  },
  {
    name: 'Large and in Charge',
    kind: 'mono',
    main: [
      { name: 'Jungle Delver', quantity: 3 },
      { name: 'Ilysian Caryatid', quantity: 4 },
      { name: 'Woodland Mystic', quantity: 2 },
      { name: 'Wildwood Patrol', quantity: 2 },
      { name: 'Baloth Packhunter', quantity: 4 },
      { name: 'Prized Unicorn', quantity: 1 },
      { name: 'Rumbling Baloth', quantity: 2 },
      { name: 'World Shaper', quantity: 1 },
      { name: 'Gigantosaurus', quantity: 2 },
      { name: 'Sentinel Spider', quantity: 2 },
      { name: 'Affectionate Indrik', quantity: 2 },
      { name: 'Rampaging Brontodon', quantity: 2 },
      { name: 'Stony Strength', quantity: 2 },
      { name: 'Rabid Bite', quantity: 3 },
      { name: 'Colossal Majesty', quantity: 2 },
      { name: 'Epic Proportions', quantity: 1 },
      { name: 'Forest', quantity: 25 },
    ],
  },
  {
    name: 'Graveyard Gifts',
    kind: 'dual',
    main: [
      { name: 'Kiora, the Rising Tide', quantity: 1 },
      { name: 'Gleaming Barrier', quantity: 3 },
      { name: 'Brineborn Cutthroat', quantity: 2 },
      { name: 'Arbiter of Woe', quantity: 2 },
      { name: 'Abyssal Harvester', quantity: 1 },
      { name: 'Crow of Dark Tidings', quantity: 2 },
      { name: 'Dreadwing Scavenger', quantity: 4 },
      { name: 'Billowing Shriekmass', quantity: 2 },
      { name: 'Arcanis the Omnipotent', quantity: 1 },
      { name: 'Opt', quantity: 4 },
      { name: 'Stab', quantity: 4 },
      { name: 'Essence Scatter', quantity: 2 },
      { name: 'Bake into a Pie', quantity: 2 },
      { name: 'Inspiration from Beyond', quantity: 2 },
      { name: 'Rise of the Dark Realms', quantity: 1 },
      { name: 'Zombify', quantity: 3 },
      { name: 'Dimir Guildgate', quantity: 4 },
      { name: 'Dismal Backwater', quantity: 4 },
      { name: 'Temple of Deceit', quantity: 1 },
      { name: 'Island', quantity: 7 },
      { name: 'Swamp', quantity: 8 },
    ],
  },
  {
    name: 'Morbid Machinations',
    kind: 'dual',
    main: [
      { name: 'Infestation Sage', quantity: 2 },
      { name: 'Llanowar Elves', quantity: 3 },
      { name: 'Eager Trufflesnout', quantity: 2 },
      { name: 'Midnight Reaper', quantity: 1 },
      { name: 'Spinner of Souls', quantity: 1 },
      { name: 'Wardens of the Cycle', quantity: 3 },
      { name: 'Cackling Prowler', quantity: 2 },
      { name: 'Vampire Gourmand', quantity: 2 },
      { name: 'Needletooth Pack', quantity: 2 },
      { name: 'Infernal Vessel', quantity: 2 },
      { name: 'Quilled Greatwurm', quantity: 1 },
      { name: 'Scavenging Ooze', quantity: 1 },
      { name: 'Wary Thespian', quantity: 2 },
      { name: 'Tragic Banshee', quantity: 2 },
      { name: 'Reassembling Skeleton', quantity: 2 },
      { name: 'Undying Malice', quantity: 2 },
      { name: 'Eaten Alive', quantity: 2 },
      { name: 'Felling Blow', quantity: 2 },
      { name: 'Vampiric Rites', quantity: 2 },
      { name: 'Forest', quantity: 8 },
      { name: 'Swamp', quantity: 7 },
      { name: 'Temple of Malady', quantity: 1 },
      { name: 'Golgari Guildgate', quantity: 4 },
      { name: 'Jungle Hollow', quantity: 4 },
    ],
  },
  {
    name: 'Reckless Raid',
    kind: 'dual',
    main: [
      { name: 'Diregraf Ghoul', quantity: 4 },
      { name: 'Infestation Sage', quantity: 3 },
      { name: 'Vampire Gourmand', quantity: 3 },
      { name: 'Searslicer Goblin', quantity: 1 },
      { name: 'Slumbering Cerberus', quantity: 3 },
      { name: 'Alesha, Who Laughs at Fate', quantity: 1 },
      { name: 'Battlesong Berserker', quantity: 2 },
      { name: 'Perforating Artist', quantity: 3 },
      { name: 'Goblin Boarders', quantity: 3 },
      { name: 'High-Society Hunter', quantity: 1 },
      { name: 'Massacre Wurm', quantity: 1 },
      { name: 'Strongbox Raider', quantity: 2 },
      { name: 'Abrade', quantity: 3 },
      { name: 'Burst Lightning', quantity: 2 },
      { name: 'Fake Your Own Death', quantity: 2 },
      { name: "Hero's Downfall", quantity: 2 },
      { name: 'Swamp', quantity: 8 },
      { name: 'Mountain', quantity: 7 },
      { name: 'Temple of Malice', quantity: 1 },
      { name: 'Bloodfell Caves', quantity: 4 },
      { name: 'Rakdos Guildgate', quantity: 4 },
    ],
  },
  {
    name: 'Arcane Aerialists',
    kind: 'dual',
    main: [
      { name: "Healer's Hawk", quantity: 2 },
      { name: 'Giada, Font of Hope', quantity: 1 },
      { name: 'Youthful Valkyrie', quantity: 2 },
      { name: 'Inspiring Overseer', quantity: 2 },
      { name: 'Serra Angel', quantity: 2 },
      { name: 'Spectral Sailor', quantity: 2 },
      { name: 'Fog Bank', quantity: 2 },
      { name: 'Curator of Destinies', quantity: 1 },
      { name: 'Empyrean Eagle', quantity: 3 },
      { name: 'Cloudblazer', quantity: 2 },
      { name: 'Dazzling Angel', quantity: 2 },
      { name: 'Aegis Turtle', quantity: 2 },
      { name: 'Vanguard Seraph', quantity: 2 },
      { name: 'High Fae Trickster', quantity: 1 },
      { name: 'Lyra Dawnbringer', quantity: 1 },
      { name: 'Faebloom Trick', quantity: 2 },
      { name: 'Chart a Course', quantity: 2 },
      { name: 'Goldvein Pick', quantity: 2 },
      { name: 'Stasis Snare', quantity: 3 },
      { name: 'Plains', quantity: 8 },
      { name: 'Island', quantity: 7 },
      { name: 'Azorius Guildgate', quantity: 4 },
      { name: 'Tranquil Cove', quantity: 4 },
      { name: 'Temple of Enlightenment', quantity: 1 },
    ],
  },
  {
    name: 'Might of the Legion',
    kind: 'dual',
    main: [
      { name: 'Frenzied Goblin', quantity: 2 },
      { name: 'Dawnwing Marshal', quantity: 2 },
      { name: 'Resolute Reinforcements', quantity: 2 },
      { name: 'Searslicer Goblin', quantity: 1 },
      { name: 'Crusader of Odric', quantity: 3 },
      { name: 'Dauntless Veteran', quantity: 2 },
      { name: 'Axgard Cavalry', quantity: 2 },
      { name: 'Krenko, Mob Boss', quantity: 1 },
      { name: 'Fanatical Firebrand', quantity: 3 },
      { name: 'Serra Angel', quantity: 2 },
      { name: 'Aurelia, the Warleader', quantity: 1 },
      { name: 'Celestial Armor', quantity: 1 },
      { name: 'Goldvein Pick', quantity: 2 },
      { name: 'Valorous Stance', quantity: 2 },
      { name: 'Burst Lightning', quantity: 2 },
      { name: 'Goblin Surprise', quantity: 2 },
      { name: 'Dragon Fodder', quantity: 2 },
      { name: 'Heroic Reinforcements', quantity: 2 },
      { name: 'Release the Dogs', quantity: 2 },
      { name: 'Mountain', quantity: 8 },
      { name: 'Plains', quantity: 9 },
      { name: 'Boros Guildgate', quantity: 2 },
      { name: 'Wind-Scarred Crag', quantity: 4 },
      { name: 'Temple of Triumph', quantity: 1 },
    ],
  },
  {
    name: 'Cat Attack',
    kind: 'dual',
    main: [
      { name: 'Savannah Lions', quantity: 3 },
      { name: 'Dawnwing Marshal', quantity: 2 },
      { name: 'Helpful Hunter', quantity: 4 },
      { name: 'Arahbo, the First Fang', quantity: 1 },
      { name: 'Regal Caracal', quantity: 1 },
      { name: 'Felidar Savior', quantity: 2 },
      { name: 'Good-Fortune Unicorn', quantity: 3 },
      { name: 'Leonin Vanguard', quantity: 3 },
      { name: 'Wary Thespian', quantity: 4 },
      { name: 'Giant Growth', quantity: 2 },
      { name: 'Claws Out', quantity: 4 },
      { name: 'Felling Blow', quantity: 2 },
      { name: 'Anthem of Champions', quantity: 1 },
      { name: 'Banishing Light', quantity: 2 },
      { name: 'Angelic Destiny', quantity: 1 },
      { name: 'Unflinching Courage', quantity: 1 },
      { name: 'Forest', quantity: 6 },
      { name: 'Plains', quantity: 9 },
      { name: 'Temple of Plenty', quantity: 1 },
      { name: 'Blossoming Sands', quantity: 4 },
      { name: 'Selesnya Guildgate', quantity: 4 },
    ],
  },
  {
    name: 'Path of Power',
    kind: 'dual',
    main: [
      { name: 'Halana and Alena, Partners', quantity: 1 },
      { name: 'Ashroot Animist', quantity: 1 },
      { name: 'Ruby, Daring Tracker', quantity: 2 },
      { name: 'Courageous Goblin', quantity: 2 },
      { name: 'Nessian Hornbeetle', quantity: 3 },
      { name: 'Axgard Cavalry', quantity: 2 },
      { name: 'Giant Cindermaw', quantity: 2 },
      { name: 'Skyraker Giant', quantity: 2 },
      { name: 'Llanowar Elves', quantity: 3 },
      { name: 'Mild-Mannered Librarian', quantity: 2 },
      { name: 'Beast-Kin Ranger', quantity: 2 },
      { name: 'Eager Trufflesnout', quantity: 2 },
      { name: 'Spinner of Souls', quantity: 1 },
      { name: 'Vizier of the Menagerie', quantity: 1 },
      { name: 'Bulk Up', quantity: 1 },
      { name: 'Scorching Dragonfire', quantity: 2 },
      { name: 'Snakeskin Veil', quantity: 2 },
      { name: 'Felling Blow', quantity: 2 },
      { name: 'Bushwhack', quantity: 2 },
      { name: "Garruk's Uprising", quantity: 1 },
      { name: 'Rugged Highlands', quantity: 4 },
      { name: 'Gruul Guildgate', quantity: 4 },
      { name: 'Mountain', quantity: 7 },
      { name: 'Forest', quantity: 8 },
      { name: 'Temple of Abandon', quantity: 1 },
    ],
  },
  {
    name: 'Wondrous Wizardry',
    kind: 'dual',
    main: [
      { name: 'Drake Hatcher', quantity: 1 },
      { name: 'Niv-Mizzet, Visionary', quantity: 1 },
      { name: 'Archmage of Runes', quantity: 1 },
      { name: 'Tolarian Terror', quantity: 3 },
      { name: 'Ghitu Lavarunner', quantity: 4 },
      { name: 'Balmor, Battlemage Captain', quantity: 1 },
      { name: 'Enigma Drake', quantity: 2 },
      { name: 'Mischievous Mystic', quantity: 2 },
      { name: 'Heartfire Immolator', quantity: 2 },
      { name: 'Ovika, Enigma Goliath', quantity: 1 },
      { name: 'Arcane Epiphany', quantity: 2 },
      { name: 'Opt', quantity: 4 },
      { name: 'Burst Lightning', quantity: 4 },
      { name: 'Dive Down', quantity: 3 },
      { name: 'Fiery Annihilation', quantity: 2 },
      { name: 'Chart a Course', quantity: 3 },
      { name: 'Mountain', quantity: 7 },
      { name: 'Island', quantity: 8 },
      { name: 'Swiftwater Cliffs', quantity: 4 },
      { name: 'Temple of Epiphany', quantity: 1 },
      { name: 'Izzet Guildgate', quantity: 4 },
    ],
  },
  {
    name: 'Vampiric Hunger',
    kind: 'dual',
    main: [
      { name: 'Hinterland Sanctifier', quantity: 2 },
      { name: "Healer's Hawk", quantity: 2 },
      { name: "Ajani's Pridemate", quantity: 3 },
      { name: 'Sun-Blessed Healer', quantity: 2 },
      { name: 'Sanguine Syphoner', quantity: 2 },
      { name: 'Vengeful Bloodwitch', quantity: 2 },
      { name: 'Cat Collector', quantity: 2 },
      { name: 'Twinblade Paladin', quantity: 2 },
      { name: 'Vampire Nighthawk', quantity: 2 },
      { name: 'Dazzling Angel', quantity: 2 },
      { name: 'Elenda, Saint of Dusk', quantity: 1 },
      { name: 'Fiendish Panda', quantity: 2 },
      { name: 'Inspiring Overseer', quantity: 2 },
      { name: 'Moment of Triumph', quantity: 2 },
      { name: 'Moment of Craving', quantity: 2 },
      { name: 'Tribute to Hunger', quantity: 2 },
      { name: 'Mortify', quantity: 2 },
      { name: 'Phyrexian Arena', quantity: 1 },
      { name: 'Angelic Destiny', quantity: 1 },
      { name: 'Plains', quantity: 8 },
      { name: 'Swamp', quantity: 7 },
      { name: 'Orzhov Guildgate', quantity: 4 },
      { name: 'Scoured Barrens', quantity: 4 },
      { name: 'Temple of Silence', quantity: 1 },
    ],
  },
  {
    name: 'Learn from the Land',
    kind: 'dual',
    main: [
      { name: 'Mischievous Mystic', quantity: 2 },
      { name: 'Exclusion Mage', quantity: 3 },
      { name: 'Mossborn Hydra', quantity: 1 },
      { name: 'Loot, Exuberant Explorer', quantity: 1 },
      { name: 'Tatyova, Benthic Druid', quantity: 2 },
      { name: 'Rampaging Baloths', quantity: 1 },
      { name: 'Apothecary Stomper', quantity: 2 },
      { name: 'Elfsworn Giant', quantity: 2 },
      { name: 'Druid of the Cowl', quantity: 4 },
      { name: 'Spectral Sailor', quantity: 2 },
      { name: 'Llanowar Elves', quantity: 3 },
      { name: 'Mild-Mannered Librarian', quantity: 2 },
      { name: 'Magnigoth Sentry', quantity: 2 },
      { name: 'Bigfin Bouncer', quantity: 2 },
      { name: 'Quick Study', quantity: 2 },
      { name: 'Felling Blow', quantity: 2 },
      { name: 'Circuitous Route', quantity: 2 },
      { name: 'Primeval Bounty', quantity: 1 },
      { name: 'Forest', quantity: 10 },
      { name: 'Island', quantity: 5 },
      { name: 'Temple of Mystery', quantity: 1 },
      { name: 'Thornwood Falls', quantity: 4 },
      { name: 'Simic Guildgate', quantity: 4 },
    ],
  },
];
